# Generated by Django 4.2.15 on 2024-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0002_jugadora_apellido_alter_jugadora_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='%d-%m-%Y'),
        ),
    ]
