# Generated by Django 4.2.15 on 2024-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0004_alter_jugadora_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
