# Generated by Django 4.2.15 on 2024-08-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0005_alter_jugadora_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
