# Generated by Django 4.2.15 on 2024-08-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0006_alter_jugadora_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='num_socia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
