# Generated by Django 4.2.15 on 2024-08-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0007_alter_jugadora_dni_alter_jugadora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='num_socia',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
