# Generated by Django 4.2.15 on 2024-09-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0008_alter_jugadora_dni_alter_jugadora_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='fecha_nacimiento',
            field=models.DateField(blank=True),
        ),
    ]
