# Generated by Django 4.2.15 on 2024-09-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0009_alter_jugadora_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='dni',
            field=models.IntegerField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='num_socia',
            field=models.IntegerField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
