# Generated by Django 4.2.15 on 2024-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0010_alter_jugadora_dni_alter_jugadora_num_socia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='dni',
            field=models.IntegerField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='num_socia',
            field=models.IntegerField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
