# Generated by Django 4.2.15 on 2024-09-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0012_alter_jugadora_num_socia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='dni',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
