# Generated by Django 4.2.15 on 2024-09-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0014_seleccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='jugadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadoras.jugadoraporano'),
        ),
    ]
