# Generated by Django 4.2.15 on 2024-12-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0015_alter_seleccion_jugadora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seleccion',
        ),
    ]
