# Generated by Django 4.2.15 on 2024-12-05 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0017_estadojugadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='estado',
            field=models.CharField(choices=[('JUEGA', 'Juega'), ('NO_JUEGA', 'No Juega'), ('LESION', 'Lesionada'), ('OTROS', 'Otros')], default='JUEGA', max_length=20),
        ),
        migrations.AlterField(
            model_name='estadojugadora',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estadojugadora',
            name='posiciones',
            field=models.CharField(default='DEF', max_length=100),
        ),
    ]
