# Generated by Django 4.2.15 on 2024-12-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0018_alter_estadojugadora_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='posiciones',
            field=models.CharField(choices=[('ARQ', 'Arquera'), ('DEF', 'Defensora'), ('VOL', 'Volante'), ('DEL', 'Delantera')], default='DEF', max_length=100),
        ),
    ]
