# Generated by Django 4.2.15 on 2024-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0019_alter_estadojugadora_posiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='posiciones',
            field=models.CharField(blank=True, choices=[('ARQ', 'Arquera'), ('DEF', 'Defensora'), ('VOL', 'Volante'), ('DEL', 'Delantera')], max_length=100),
        ),
    ]
