# Generated by Django 4.2.15 on 2024-12-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0020_alter_estadojugadora_posiciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='posiciones',
            field=models.CharField(choices=[('ARQ', 'Arquera'), ('DEF', 'Defensora'), ('VOL', 'Volante'), ('DEL', 'Delantera')], default='DEF', help_text='Seleccione múltiples posiciones', max_length=100),
        ),
    ]
