# Generated by Django 4.2.15 on 2024-12-06 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0023_tiposestado_remove_estadojugadora_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2024, 12, 6, 13, 55, 54, 975447, tzinfo=datetime.timezone.utc)),
        ),
    ]
