# Generated by Django 4.2.15 on 2024-12-06 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jugadoras', '0024_alter_estadojugadora_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadojugadora',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
